### PR TITLE
Moved C# client to separate repo. Made formatting changes

### PR DESCRIPTION
**Pull request by ncthbrt**
Hi guys. I know you added comments to the original repo. But I've now moved it and made the formatting changes Henk requested. Hopefully you guys can approve this so we can pull it out of inprogress

### CODE REVIEW

**Comment by ncthbrt** [comment]
Acceptance criteria:

- Runs on C# >= 4.5
- Handles client side authentication
- Needs to be able to handle reconnection events 
- Availability on public nuget
- API reference documentation

**Comment by Lutando** [comment]
Looks good to me.

**Comment by hendrikdelarey** [comment]
:shipit:

**Comment by ncthbrt** [comment]
Will bump the version number and then merge

**Pull request merged**
